### PR TITLE
Screenshot region

### PR DESCRIPTION
**Pull request by selairi**
This PR only adds an option to capture an area of the screen.

### CODE REVIEW

**Comment by tsujan** [comment]
Nice work! This is a great addition to lximage-qt and works as intended.

I read the code yesterday (while doing other works but will reread it again) and didn't find any problem. Just two minor things:

(1) @selairi, could you please use the actual highlight color insted of `Qt::green` in `screenshotselectareagraphicsview.cpp`, like this:
````
...
    if(selectedAreaRect == nullptr) {
      QColor highlight = palette().color(QPalette::Active,QPalette::Highlight);
      QPen pen(highlight, 3, Qt::DashDotLine, Qt::RoundCap, Qt::RoundJoin);
      QColor color(highlight);
      color.setAlpha(128);
...
````
Green is good but, IMO, it's better to follow the active Qt widget style.

(2) The coding style of lximage-qt is so that private variables have an ending underline (like `image_` instead of `image`). @selairi, could you do the same thing in your code?

**Comment by selairi** [comment]
(1) @selairi <https://github.com/selairi>, could you please use the actual
> highlight color insted of Qt::green in screenshotselectareagraphicsvi
> ew.cpp, like this:
>
 Ok. I will change it.

>
> (2) The coding style of lximage-qt is so that private variables have an
> ending underline (like image_ instead of image). @selairi
> <https://github.com/selairi>, could you do the same thing in your code?
>
Yes, of course.

Thanks for your revision and suggestions.

**Comment by selairi** [comment]
All changes have been implemented. :-)

2017-01-31 22:39 GMT+01:00 P L. Lucas <selairi@gmail.com>:

>
>
> (1) @selairi <https://github.com/selairi>, could you please use the
>> actual highlight color insted of Qt::green in
>> screenshotselectareagraphicsview.cpp, like this:
>>
>  Ok. I will change it.
>
>>
>> (2) The coding style of lximage-qt is so that private variables have an
>> ending underline (like image_ instead of image). @selairi
>> <https://github.com/selairi>, could you do the same thing in your code?
>>
> Yes, of course.
>
> Thanks for your revision and suggestions.
>
>

**Comment by tsujan** [comment]
IMO, `screenshotselectareagraphicsview.cpp` can be made simpler. Please check if these are correct (I may be wrong):

**(1)** Instead of
````
selectedAreaRect_ = scene()->addRect(p_x0_, p_y0_, p_x0_, p_y0_, pen, brush);
````
you could simply write:
````
selectedAreaRect_ = scene()->addRect(QRectF(), pen, brush);
````

**(2)** `ScreenshotSelectAreaGraphicsView::mouseReleaseEvent()` can be simplified as:
````
void ScreenshotSelectAreaGraphicsView::mouseReleaseEvent(QMouseEvent *event)
{
  Q_EMIT selectedArea(rectPositionAndSize(event->x(),event->y()).toRect());
}
````

**(3)** `ScreenshotSelectAreaGraphicsView::rectPositionAndSize()` can be simplified too:
````

QRectF ScreenshotSelectAreaGraphicsView::rectPositionAndSize(int x, int y)
{

  return QRectF(qMin((qreal)x, p_x0_), qMin((qreal)y, p_y0_),
                qAbs(x - p_x0_), qAbs(y - p_y0_));
}
````

**(4)** Also a single QPointF `p0_` could be used in place of `p_x0_` and `p_y0_` but I didn't try it. Please check!

**Comment by selairi** [comment]
I have applied your suggestions and I have found that QPointF class makes
the code simpler.

Thanks again.

2017-02-01 12:34 GMT+01:00 tsujan <notifications@github.com>:

**Comment by tsujan** [comment]
Great! You made it even simpler :)

**Comment by tsujan** [comment]
IMO, it can be merged but let's wait a week to see if anyone finds a problem. GTM.

**Comment by selairi** [comment]
OK

2017-02-01 13:35 GMT+01:00 tsujan <notifications@github.com>:

**Comment by tsujan** [comment]
Merged to get feedback. Thanks!

**Pull request merged**
