### PR TITLE
Bump versions

### PR DESCRIPTION
**Pull request by agaida**
Remove some QUIET

### CODE REVIEW

**Comment by tsujan** [comment]
Yes, I also think `QUIET` should have been removed in those cases. GTM.

**Comment by tsujan** [comment]
... Or the SVG dependency could be loosened but I see no practical reason for that.

**Comment by agaida** [comment]
There is a bug for it - removing the QUIETs - if we really want some components optional there are better ways - like options.

**Comment by palinek** [comment]
> if we really want some components optional there are better ways - like options.

QUIET isn't about making the dependency optional... but about not-writing information about found package during the build phase

**Comment by palinek** [comment]
GTM

**Comment by tsujan** [comment]
> QUIET isn't about making the dependency optional... but about not-writing information about found package during the build phase

... which can be used best with optional dependencies.

Anyhow, I don't think we need optional features here.

**Comment by agaida** [comment]
@palinek  - right, i know - and i really hate this kind of CMakeFiles that work wit if found - and i really like the straight forward approach - find has to fail if a component that i want to have isn't there - if i use QUIET i can only hope that it will be checked/handled later.

**Pull request merged**
