### PR TITLE
Update loadimagejob.cpp

### PR DESCRIPTION
**Pull request by brunobenet8**
Lack of parentheses...

### CODE REVIEW

**Comment by palinek** [comment]
1. with your patch the sources aren't compilable
2. why do you think, there is the brace missing?

**Comment by brunobenet8** [comment]
Hi, well, has many parts of the code without brace, in the "if" never
starts, so i changed some parts, but still is incomplete.

Em 17/07/2017 3:07 AM, "palinek" <notifications@github.com> escreveu:


   1. with your patch the sources aren't compilable
   2. why do you think, there is the brace missing?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lxde/lximage-qt/pull/103#issuecomment-315674302>, or mute
the thread

**Comment by palinek** [comment]
This is simply wrong... you're trying to talk about the coding style, but with this PR you broke the app and it isn't even compilable.... so closing

**Comment by tsujan** [comment]
@brunobenet8 We don't have an obsession with braces.

**Comment by brunobenet8** [comment]
Hi, sorry that changes, was that i make a fork from project because i use
the lubuntu how my main system and i need that the image view send e-mail
from the file images, but in debugger never compile, so they show the
missing braces, so sorry that i changes before input the new code.

2017-07-19 6:54 GMT-03:00 tsujan <notifications@github.com>:

**Comment by tsujan** [comment]
> but in debugger never compile,

Your system should have another problem. There's no missing braces in any LXQt source.

**Pull request closed without merging**
