### PR TITLE
Adapt to changes in libfm-qt(the c++11 port)

### PR DESCRIPTION
**Pull request by palinek**
ref lxde/libfm-qt#63

Just a poor try..., but it compiles and shows the images :)

There are still some newly added TODOs... 

@tsujan @PCMan, please, review and make any needed corrections

### CODE REVIEW

**Comment by tsujan** [comment]
I haven't read the code yet but it works as intended. Good job!

GTM after the new libfm-qt is merged.

**Comment by palinek** [comment]
> GTM after the new libfm-qt is merged.

It's not ready yet, we need to address at least the error handling in load/save jobs.

**Comment by tsujan** [comment]
> It's not ready yet, we need to address at least the error handling in load/save jobs.

OK. I meant it for not losing lximage-qt after merging the new libfm-qt -- as wed don't now, thanks to your work -- otherwise the new pcmanfm-qt and libfm-qt might also need changes/fixes.

**Comment by palinek** [comment]
Now I think it should be ready for merging...

**Pull request merged**
